/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Usuario;
import ConexaoBD.UsuarioBD;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Cadastro extends javax.swing.JFrame {
       Usuario usuario = new Usuario ();
    UsuarioBD usuarioBD = new UsuarioBD ();
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Nome = new javax.swing.JTextField();
        jtf_Cidade = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jtf_Email = new javax.swing.JTextField();
        jtf_Usuario = new javax.swing.JTextField();
        jtf_Senha = new javax.swing.JTextField();
        jtf_Bairro = new javax.swing.JTextField();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        jtf_Cancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        JlCidade = new javax.swing.JLabel();
        JlTelefone = new javax.swing.JLabel();
        JlUsuario = new javax.swing.JLabel();
        JlEstado = new javax.swing.JLabel();
        JlEmail = new javax.swing.JLabel();
        JlSenha = new javax.swing.JLabel();
        jLabel_logo_OLX = new javax.swing.JLabel();
        JlTopobackground = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        Jlbackground = new javax.swing.JLabel();

        jTextField11.setText("jTextField11");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1025, 627));
        setMinimumSize(new java.awt.Dimension(1025, 627));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1025, 627));
        setResizable(false);
        setSize(new java.awt.Dimension(1025, 627));
        getContentPane().setLayout(null);

        jtf_Estado.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Estado.setBorder(null);
        getContentPane().add(jtf_Estado);
        jtf_Estado.setBounds(110, 280, 310, 20);

        jtf_Nome.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Nome.setBorder(null);
        jtf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Nome);
        jtf_Nome.setBounds(110, 150, 460, 20);

        jtf_Cidade.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Cidade.setBorder(null);
        getContentPane().add(jtf_Cidade);
        jtf_Cidade.setBounds(110, 338, 310, 23);

        jtfTelefone.setBackground(new java.awt.Color(242, 242, 242));
        jtfTelefone.setBorder(null);
        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        getContentPane().add(jtfTelefone);
        jtfTelefone.setBounds(650, 220, 250, 20);

        jtf_Email.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Email.setBorder(null);
        getContentPane().add(jtf_Email);
        jtf_Email.setBounds(650, 150, 320, 20);

        jtf_Usuario.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Usuario.setBorder(null);
        getContentPane().add(jtf_Usuario);
        jtf_Usuario.setBounds(660, 290, 200, 20);

        jtf_Senha.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Senha.setBorder(null);
        getContentPane().add(jtf_Senha);
        jtf_Senha.setBounds(660, 340, 200, 20);

        jtf_Bairro.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Bairro.setBorder(null);
        getContentPane().add(jtf_Bairro);
        jtf_Bairro.setBounds(110, 220, 310, 20);

        jLabelNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeCompleto.setText("Nome:");
        getContentPane().add(jLabelNomeCompleto);
        jLabelNomeCompleto.setBounds(38, 150, 60, 17);

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCidade.setText("Cidade:");
        getContentPane().add(jLabelCidade);
        jLabelCidade.setBounds(40, 340, 70, 17);

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBairro.setText("Bairro:");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(40, 220, 50, 17);

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(40, 280, 70, 17);

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefone.setText("Telefone:");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(570, 220, 70, 20);

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(590, 150, 50, 17);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(580, 290, 50, 17);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(590, 340, 43, 17);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Botao fechar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(970, 0, 40, 50);

        btn_Cadastrar.setBackground(new java.awt.Color(242, 242, 242));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        btn_Cadastrar.setBorder(null);
        btn_Cadastrar.setContentAreaFilled(false);
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cadastrar);
        btn_Cadastrar.setBounds(410, 450, 65, 70);

        jtf_Cancelar.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel icon.png"))); // NOI18N
        jtf_Cancelar.setBorderPainted(false);
        jtf_Cancelar.setContentAreaFilled(false);
        jtf_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Cancelar);
        jtf_Cancelar.setBounds(510, 450, 97, 70);

        jLabelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Nome.png"))); // NOI18N
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(100, 140, 480, 40);

        JlCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Cidade.png"))); // NOI18N
        getContentPane().add(JlCidade);
        JlCidade.setBounds(100, 330, 340, 34);

        JlTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo telefone.png"))); // NOI18N
        getContentPane().add(JlTelefone);
        JlTelefone.setBounds(640, 210, 350, 34);

        JlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo user.png"))); // NOI18N
        getContentPane().add(JlUsuario);
        JlUsuario.setBounds(650, 280, 230, 34);

        JlEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo estado.png"))); // NOI18N
        getContentPane().add(JlEstado);
        JlEstado.setBounds(100, 270, 340, 40);

        JlEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Email.png"))); // NOI18N
        getContentPane().add(JlEmail);
        JlEmail.setBounds(640, 140, 350, 34);

        JlSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Senha2.png"))); // NOI18N
        getContentPane().add(JlSenha);
        JlSenha.setBounds(650, 330, 230, 34);

        jLabel_logo_OLX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo novo.png"))); // NOI18N
        getContentPane().add(jLabel_logo_OLX);
        jLabel_logo_OLX.setBounds(10, 0, 50, 41);

        JlTopobackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tela superior.png"))); // NOI18N
        getContentPane().add(JlTopobackground);
        JlTopobackground.setBounds(0, 0, 1030, 50);

        jLBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Bairro.png"))); // NOI18N
        getContentPane().add(jLBairro);
        jLBairro.setBounds(100, 210, 340, 40);

        Jlbackground.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jlbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpeg"))); // NOI18N
        getContentPane().add(Jlbackground);
        Jlbackground.setBounds(0, 0, 1030, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CancelarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jtf_CancelarActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
          usuario.setBairro(jtf_Bairro.getText());
          usuario.setCidade(jtf_Cidade.getText());
          usuario.setNome(jtf_Nome.getText());
          usuario.setEmail(jtf_Email.getText());
          usuario.setTelefone(jtfTelefone.getText());
          usuario.setUF(jtf_Estado.getText());
          usuario.setUsuario(jtf_Usuario.getText());
          usuario.setSenha(jtf_Senha.getText());
                   
          try {
                            usuarioBD.inserir(usuario);
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this, "Erro ao inserir Usuário.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                        }
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso");
        
        Login login = new Login();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlCidade;
    private javax.swing.JLabel JlEmail;
    private javax.swing.JLabel JlEstado;
    private javax.swing.JLabel JlSenha;
    private javax.swing.JLabel JlTelefone;
    private javax.swing.JLabel JlTopobackground;
    private javax.swing.JLabel JlUsuario;
    private javax.swing.JLabel Jlbackground;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabel_logo_OLX;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JTextField jtf_Bairro;
    private javax.swing.JButton jtf_Cancelar;
    private javax.swing.JTextField jtf_Cidade;
    private javax.swing.JTextField jtf_Email;
    private javax.swing.JTextField jtf_Estado;
    private javax.swing.JTextField jtf_Nome;
    private javax.swing.JTextField jtf_Senha;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
}
