/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelDataDeNascimento = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jtf_Nome = new javax.swing.JTextField();
        jtf_Data = new javax.swing.JTextField();
        jtf_CPF = new javax.swing.JTextField();
        jtf_Rua = new javax.swing.JTextField();
        jtf_Cidade = new javax.swing.JTextField();
        jtf_Bairro = new javax.swing.JTextField();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Telefone = new javax.swing.JTextField();
        jtf_Email = new javax.swing.JTextField();
        jtf_Usuario = new javax.swing.JTextField();
        jtf_Senha = new javax.swing.JTextField();
        btn_Cadastrar = new javax.swing.JButton();
        jtf_Cancelar = new javax.swing.JButton();

        jTextField11.setText("jTextField11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1369, 730));
        getContentPane().setLayout(null);

        jLabelNomeCompleto.setText("Nome Completo");
        getContentPane().add(jLabelNomeCompleto);
        jLabelNomeCompleto.setBounds(20, 40, 91, 16);

        jLabelDataDeNascimento.setText("Data de Nascimento");
        getContentPane().add(jLabelDataDeNascimento);
        jLabelDataDeNascimento.setBounds(10, 61, 114, 16);

        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(87, 87, 22, 16);

        jLabelRua.setText("Rua");
        getContentPane().add(jLabelRua);
        jLabelRua.setBounds(87, 113, 22, 16);

        jLabelCidade.setText("Cidade");
        getContentPane().add(jLabelCidade);
        jLabelCidade.setBounds(73, 139, 39, 16);

        jLabelBairro.setText("Bairro");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(78, 165, 34, 16);

        jLabelEstado.setText("Estado");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(73, 191, 38, 16);

        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(63, 217, 50, 16);

        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(81, 243, 31, 16);

        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(69, 269, 43, 16);

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(75, 295, 36, 16);

        jtf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Nome);
        jtf_Nome.setBounds(116, 32, 174, 22);
        getContentPane().add(jtf_Data);
        jtf_Data.setBounds(116, 58, 174, 22);
        getContentPane().add(jtf_CPF);
        jtf_CPF.setBounds(116, 84, 174, 22);
        getContentPane().add(jtf_Rua);
        jtf_Rua.setBounds(116, 110, 174, 22);
        getContentPane().add(jtf_Cidade);
        jtf_Cidade.setBounds(116, 136, 174, 22);
        getContentPane().add(jtf_Bairro);
        jtf_Bairro.setBounds(116, 162, 174, 22);
        getContentPane().add(jtf_Estado);
        jtf_Estado.setBounds(116, 188, 174, 22);
        getContentPane().add(jtf_Telefone);
        jtf_Telefone.setBounds(115, 214, 175, 22);
        getContentPane().add(jtf_Email);
        jtf_Email.setBounds(115, 240, 175, 22);
        getContentPane().add(jtf_Usuario);
        jtf_Usuario.setBounds(115, 266, 175, 22);
        getContentPane().add(jtf_Senha);
        jtf_Senha.setBounds(115, 292, 175, 22);

        btn_Cadastrar.setBackground(new java.awt.Color(169, 45, 215));
        btn_Cadastrar.setText("Cadastrar");
        getContentPane().add(btn_Cadastrar);
        btn_Cadastrar.setBounds(115, 330, 89, 25);

        jtf_Cancelar.setText("Cancelar");
        getContentPane().add(jtf_Cancelar);
        jtf_Cancelar.setBounds(214, 330, 83, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataDeNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jtf_Bairro;
    private javax.swing.JTextField jtf_CPF;
    private javax.swing.JButton jtf_Cancelar;
    private javax.swing.JTextField jtf_Cidade;
    private javax.swing.JTextField jtf_Data;
    private javax.swing.JTextField jtf_Email;
    private javax.swing.JTextField jtf_Estado;
    private javax.swing.JTextField jtf_Nome;
    private javax.swing.JTextField jtf_Rua;
    private javax.swing.JTextField jtf_Senha;
    private javax.swing.JTextField jtf_Telefone;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
}
