/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelDataDeNascimento = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jtf_Nome = new javax.swing.JTextField();
        jtf_Data = new javax.swing.JTextField();
        jtf_CPF = new javax.swing.JTextField();
        jtf_Rua = new javax.swing.JTextField();
        jtf_Cidade = new javax.swing.JTextField();
        jtf_Bairro = new javax.swing.JTextField();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Telefone = new javax.swing.JTextField();
        jtf_Email = new javax.swing.JTextField();
        jtf_Usuario = new javax.swing.JTextField();
        jtf_Senha = new javax.swing.JTextField();
        btn_Cadastrar = new javax.swing.JButton();
        jtf_Cancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField11.setText("jTextField11");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 728));
        getContentPane().setLayout(null);

        jLabelNomeCompleto.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelNomeCompleto.setText("Nome Completo");
        getContentPane().add(jLabelNomeCompleto);
        jLabelNomeCompleto.setBounds(80, 80, 113, 17);

        jLabelDataDeNascimento.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelDataDeNascimento.setText("Data de Nascimento");
        getContentPane().add(jLabelDataDeNascimento);
        jLabelDataDeNascimento.setBounds(710, 80, 141, 17);

        jLabelCPF.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(160, 140, 40, 17);

        jLabelRua.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelRua.setText("Rua");
        getContentPane().add(jLabelRua);
        jLabelRua.setBounds(160, 220, 30, 17);

        jLabelCidade.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelCidade.setText("Cidade");
        getContentPane().add(jLabelCidade);
        jLabelCidade.setBounds(140, 260, 49, 17);

        jLabelBairro.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelBairro.setText("Bairro");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(770, 160, 50, 17);

        jLabelEstado.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(770, 200, 50, 17);

        jLabelTelefone.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(130, 310, 60, 20);

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(780, 250, 50, 17);

        jLabelUsuario.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(130, 350, 60, 17);

        jLabelSenha.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(780, 290, 60, 17);

        jtf_Nome.setBorder(null);
        jtf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Nome);
        jtf_Nome.setBounds(220, 80, 460, 20);
        getContentPane().add(jtf_Data);
        jtf_Data.setBounds(860, 80, 174, 20);

        jtf_CPF.setBorder(null);
        getContentPane().add(jtf_CPF);
        jtf_CPF.setBounds(220, 140, 320, 20);
        getContentPane().add(jtf_Rua);
        jtf_Rua.setBounds(200, 220, 174, 20);
        getContentPane().add(jtf_Cidade);
        jtf_Cidade.setBounds(200, 260, 174, 20);
        getContentPane().add(jtf_Bairro);
        jtf_Bairro.setBounds(830, 160, 174, 20);
        getContentPane().add(jtf_Estado);
        jtf_Estado.setBounds(830, 200, 174, 20);
        getContentPane().add(jtf_Telefone);
        jtf_Telefone.setBounds(200, 310, 175, 20);
        getContentPane().add(jtf_Email);
        jtf_Email.setBounds(840, 250, 175, 20);
        getContentPane().add(jtf_Usuario);
        jtf_Usuario.setBounds(200, 350, 175, 20);
        getContentPane().add(jtf_Senha);
        jtf_Senha.setBounds(840, 290, 175, 20);

        btn_Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        getContentPane().add(btn_Cadastrar);
        btn_Cadastrar.setBounds(310, 400, 97, 70);

        jtf_Cancelar.setBackground(new java.awt.Color(169, 45, 205));
        jtf_Cancelar.setText("Cancelar");
        getContentPane().add(jtf_Cancelar);
        jtf_Cancelar.setBounds(510, 430, 75, 23);

        jLabelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Nome.png"))); // NOI18N
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(210, 70, 480, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo CPF.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 130, 340, 34);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataDeNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jtf_Bairro;
    private javax.swing.JTextField jtf_CPF;
    private javax.swing.JButton jtf_Cancelar;
    private javax.swing.JTextField jtf_Cidade;
    private javax.swing.JTextField jtf_Data;
    private javax.swing.JTextField jtf_Email;
    private javax.swing.JTextField jtf_Estado;
    private javax.swing.JTextField jtf_Nome;
    private javax.swing.JTextField jtf_Rua;
    private javax.swing.JTextField jtf_Senha;
    private javax.swing.JTextField jtf_Telefone;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
}
