/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class CardLayout extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public CardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_fechar = new javax.swing.JButton();
        BarraTop = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        bt_meuCadastro = new javax.swing.JButton();
        bt_desapegar = new javax.swing.JButton();
        bt_meusPedidos = new javax.swing.JButton();
        bt_meusAnuncios = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();
        Cadastro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jl_valor = new javax.swing.JLabel();
        jtf_valor = new javax.swing.JTextField();
        jl_condicaoProduto = new javax.swing.JLabel();
        jrb_Novo = new javax.swing.JRadioButton();
        jrb_Usado = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1369, 730));
        setMinimumSize(new java.awt.Dimension(1369, 730));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1369, 730));
        getContentPane().setLayout(null);

        bt_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Botao fechar.png"))); // NOI18N
        bt_fechar.setBorder(null);
        bt_fechar.setBorderPainted(false);
        bt_fechar.setContentAreaFilled(false);
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });
        getContentPane().add(bt_fechar);
        bt_fechar.setBounds(1316, 0, 50, 50);

        BarraTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra superior.png"))); // NOI18N
        getContentPane().add(BarraTop);
        BarraTop.setBounds(0, 0, 1370, 50);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo-3D.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(10, 60, 100, 100);

        nomeUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeUser.setText("Nome do usuário aqui");
        getContentPane().add(nomeUser);
        nomeUser.setBounds(120, 100, 210, 22);

        bt_meuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon meu cadastro.png"))); // NOI18N
        bt_meuCadastro.setBorder(null);
        bt_meuCadastro.setBorderPainted(false);
        bt_meuCadastro.setContentAreaFilled(false);
        bt_meuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_meuCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(bt_meuCadastro);
        bt_meuCadastro.setBounds(-7, 200, 310, 63);

        bt_desapegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon desapega.png"))); // NOI18N
        bt_desapegar.setBorder(null);
        bt_desapegar.setBorderPainted(false);
        bt_desapegar.setContentAreaFilled(false);
        getContentPane().add(bt_desapegar);
        bt_desapegar.setBounds(-7, 310, 310, 63);

        bt_meusPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon anuncios reservados.png"))); // NOI18N
        bt_meusPedidos.setBorder(null);
        bt_meusPedidos.setBorderPainted(false);
        bt_meusPedidos.setContentAreaFilled(false);
        getContentPane().add(bt_meusPedidos);
        bt_meusPedidos.setBounds(-7, 420, 310, 63);

        bt_meusAnuncios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Meus anuncios.png"))); // NOI18N
        bt_meusAnuncios.setBorder(null);
        bt_meusAnuncios.setBorderPainted(false);
        bt_meusAnuncios.setContentAreaFilled(false);
        getContentPane().add(bt_meusAnuncios);
        bt_meusAnuncios.setBounds(-7, 530, 310, 63);

        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon Sair.png"))); // NOI18N
        bt_sair.setBorder(null);
        bt_sair.setBorderPainted(false);
        bt_sair.setContentAreaFilled(false);
        getContentPane().add(bt_sair);
        bt_sair.setBounds(-7, 640, 310, 70);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fundo menu.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 340, 730);

        Cadastro.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Novo desapego");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(420, 40, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Foto.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 130, 290, 340);

        jLabel3.setText("Titulo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(490, 150, 41, 16);

        jtf_titulo.setBackground(new java.awt.Color(242, 242, 242));
        jtf_titulo.setBorder(null);
        jPanel2.add(jtf_titulo);
        jtf_titulo.setBounds(570, 150, 360, 16);

        jLabel4.setText("Descricão");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(470, 200, 60, 16);

        jl_valor.setText("Valor");
        jPanel2.add(jl_valor);
        jl_valor.setBounds(490, 450, 30, 16);

        jtf_valor.setBackground(new java.awt.Color(242, 242, 242));
        jtf_valor.setBorder(null);
        jPanel2.add(jtf_valor);
        jtf_valor.setBounds(560, 450, 200, 16);

        jl_condicaoProduto.setText("O produto é");
        jPanel2.add(jl_condicaoProduto);
        jl_condicaoProduto.setBounds(482, 505, 100, 16);

        jrb_Novo.setText("Novo");
        jrb_Novo.setContentAreaFilled(false);
        jPanel2.add(jrb_Novo);
        jrb_Novo.setBounds(570, 500, 57, 25);

        jrb_Usado.setText("Usado");
        jrb_Usado.setContentAreaFilled(false);
        jPanel2.add(jrb_Usado);
        jrb_Usado.setBounds(630, 500, 63, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inserir foto icon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel2.add(jButton1);
        jButton1.setBounds(150, 510, 130, 33);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit icon.png"))); // NOI18N
        btn_edit.setBorder(null);
        btn_edit.setBorderPainted(false);
        btn_edit.setContentAreaFilled(false);
        jPanel2.add(btn_edit);
        btn_edit.setBounds(420, 570, 65, 80);

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        jPanel2.add(btn_save);
        btn_save.setBounds(530, 570, 65, 80);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(570, 200, 360, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Titulo.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(560, 140, 390, 34);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Senha.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(550, 440, 220, 34);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo descricao.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(560, 190, 390, 220);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íco-Imovel copiar 6.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, -40, 1040, 740);

        Cadastro.add(jPanel2, "card2");

        getContentPane().add(Cadastro);
        Cadastro.setBounds(340, 50, 1030, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_meuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_meuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_meuCadastroActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraTop;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton bt_desapegar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_meuCadastro;
    private javax.swing.JButton bt_meusAnuncios;
    private javax.swing.JButton bt_meusPedidos;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jl_condicaoProduto;
    private javax.swing.JLabel jl_valor;
    private javax.swing.JRadioButton jrb_Novo;
    private javax.swing.JRadioButton jrb_Usado;
    private javax.swing.JTextField jtf_titulo;
    private javax.swing.JTextField jtf_valor;
    private javax.swing.JLabel nomeUser;
    // End of variables declaration//GEN-END:variables
}
