/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class CardLayout extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public CardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ___ = new javax.swing.JButton();
        Venda = new javax.swing.JPanel();
        Reserva = new javax.swing.JPanel();
        btn_aceitar = new javax.swing.JButton();
        btn_recusar = new javax.swing.JButton();
        Anuncio = new javax.swing.JPanel();
        jtf_EstadoConservacao = new javax.swing.JTextField();
        jtf_EstadoQueMoro = new javax.swing.JTextField();
        jtf_FotoProduto = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        jLabel_Nome = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        jLabel_preco = new javax.swing.JLabel();
        jLabel_conservacao = new javax.swing.JLabel();
        jLabel_estadoVenda = new javax.swing.JLabel();
        jLabel_Imagem = new javax.swing.JLabel();
        jtf_NomeProduto = new javax.swing.JTextField();
        jtf_PrecoProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Exibir anuncio");
        inicial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 149, 106));

        jLabel2.setText("Exibir anuncio");
        inicial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 149, 106));

        jLabel3.setText("Exibir anuncio");
        inicial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 149, 106));

        jLabel4.setText("Exibir anuncio");
        inicial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 149, 106));

        jLabel5.setText("Exibir anuncio");
        inicial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 149, 106));

        ___.setText("___");
        inicial.add(___, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        getContentPane().add(inicial, "card3");

        javax.swing.GroupLayout VendaLayout = new javax.swing.GroupLayout(Venda);
        Venda.setLayout(VendaLayout);
        VendaLayout.setHorizontalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        VendaLayout.setVerticalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        getContentPane().add(Venda, "card2");

        btn_aceitar.setText("Aceitar");

        btn_recusar.setText("Recusar");

        javax.swing.GroupLayout ReservaLayout = new javax.swing.GroupLayout(Reserva);
        Reserva.setLayout(ReservaLayout);
        ReservaLayout.setHorizontalGroup(
            ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservaLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_aceitar)
                .addGap(82, 82, 82)
                .addComponent(btn_recusar)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        ReservaLayout.setVerticalGroup(
            ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservaLayout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addGroup(ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceitar)
                    .addComponent(btn_recusar))
                .addGap(68, 68, 68))
        );

        getContentPane().add(Reserva, "card4");

        btn_cadastrar.setText("Cadastrar");

        jLabel_Nome.setText("Nome do produto");

        btn_cancelar.setText("Cancelar");

        jLabel_preco.setText("Preço do produto");

        jLabel_conservacao.setText("Estado de conservação");

        jLabel_estadoVenda.setText("Estado que moro");

        jLabel_Imagem.setText("Foto do produto");

        javax.swing.GroupLayout AnuncioLayout = new javax.swing.GroupLayout(Anuncio);
        Anuncio.setLayout(AnuncioLayout);
        AnuncioLayout.setHorizontalGroup(
            AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnuncioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnuncioLayout.createSequentialGroup()
                        .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_estadoVenda)
                            .addComponent(jLabel_Nome)
                            .addComponent(jLabel_preco)
                            .addComponent(jLabel_conservacao))
                        .addGap(18, 18, 18)
                        .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_NomeProduto)
                            .addComponent(jtf_PrecoProduto)
                            .addComponent(jtf_EstadoConservacao)
                            .addComponent(jtf_EstadoQueMoro, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AnuncioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_Imagem)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_FotoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnuncioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)
                        .addGap(30, 30, 30)))
                .addGap(35, 35, 35))
        );
        AnuncioLayout.setVerticalGroup(
            AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnuncioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Imagem)
                    .addComponent(jtf_FotoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jtf_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_preco)
                    .addComponent(jtf_PrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_conservacao)
                    .addComponent(jtf_EstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_estadoVenda)
                    .addComponent(jtf_EstadoQueMoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cancelar))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        getContentPane().add(Anuncio, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anuncio;
    private javax.swing.JPanel Reserva;
    private javax.swing.JPanel Venda;
    private javax.swing.JButton ___;
    private javax.swing.JButton btn_aceitar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_recusar;
    private javax.swing.JPanel inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Imagem;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_conservacao;
    private javax.swing.JLabel jLabel_estadoVenda;
    private javax.swing.JLabel jLabel_preco;
    private javax.swing.JTextField jtf_EstadoConservacao;
    private javax.swing.JTextField jtf_EstadoQueMoro;
    private javax.swing.JTextField jtf_FotoProduto;
    private javax.swing.JTextField jtf_NomeProduto;
    private javax.swing.JTextField jtf_PrecoProduto;
    // End of variables declaration//GEN-END:variables
}
