/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class CardLayout extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public CardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ___ = new javax.swing.JButton();
        Venda = new javax.swing.JPanel();
        Reserva = new javax.swing.JPanel();
        btn_aceitar = new javax.swing.JButton();
        btn_recusar = new javax.swing.JButton();
        Anuncio = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jLabel_preco = new javax.swing.JLabel();
        jLabel_conservacao = new javax.swing.JLabel();
        jLabel_estadoVenda = new javax.swing.JLabel();
        jl_Imagem = new javax.swing.JLabel();
        jl_img = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_campoDescricao = new javax.swing.JLabel();
        jtf_NomeProduto = new javax.swing.JTextField();
        jtf_PrecoProduto = new javax.swing.JTextField();
        jtf_NomeProduto1 = new javax.swing.JTextField();
        jRB_Novo = new javax.swing.JRadioButton();
        jRB_usado = new javax.swing.JRadioButton();
        jcb_estado = new javax.swing.JComboBox<>();
        btn_Editar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Exibir anuncio");
        inicial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 149, 106));

        jLabel2.setText("Exibir anuncio");
        inicial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 149, 106));

        jLabel3.setText("Exibir anuncio");
        inicial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 149, 106));

        jLabel4.setText("Exibir anuncio");
        inicial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 149, 106));

        jLabel5.setText("Exibir anuncio");
        inicial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 149, 106));

        ___.setText("___");
        inicial.add(___, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        getContentPane().add(inicial, "card3");

        javax.swing.GroupLayout VendaLayout = new javax.swing.GroupLayout(Venda);
        Venda.setLayout(VendaLayout);
        VendaLayout.setHorizontalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        VendaLayout.setVerticalGroup(
            VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        getContentPane().add(Venda, "card2");

        btn_aceitar.setText("Aceitar");

        btn_recusar.setText("Recusar");

        javax.swing.GroupLayout ReservaLayout = new javax.swing.GroupLayout(Reserva);
        Reserva.setLayout(ReservaLayout);
        ReservaLayout.setHorizontalGroup(
            ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservaLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_aceitar)
                .addGap(82, 82, 82)
                .addComponent(btn_recusar)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        ReservaLayout.setVerticalGroup(
            ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservaLayout.createSequentialGroup()
                .addContainerGap(637, Short.MAX_VALUE)
                .addGroup(ReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceitar)
                    .addComponent(btn_recusar))
                .addGap(68, 68, 68))
        );

        getContentPane().add(Reserva, "card4");

        Anuncio.setMaximumSize(new java.awt.Dimension(1025, 728));
        Anuncio.setMinimumSize(new java.awt.Dimension(1025, 728));
        Anuncio.setLayout(null);

        jl_titulo.setText("Titulo:");
        Anuncio.add(jl_titulo);
        jl_titulo.setBounds(340, 120, 30, 14);

        jLabel_preco.setText("Preço do produto:");
        Anuncio.add(jLabel_preco);
        jLabel_preco.setBounds(300, 400, 87, 14);

        jLabel_conservacao.setText("O produto é");
        Anuncio.add(jLabel_conservacao);
        jLabel_conservacao.setBounds(310, 480, 58, 14);

        jLabel_estadoVenda.setText("Estado:");
        Anuncio.add(jLabel_estadoVenda);
        jLabel_estadoVenda.setBounds(650, 400, 37, 14);

        jl_Imagem.setText("Foto do produto");
        Anuncio.add(jl_Imagem);
        jl_Imagem.setBounds(32, 468, 78, 14);

        jl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Foto.png"))); // NOI18N
        Anuncio.add(jl_img);
        jl_img.setBounds(10, 96, 284, 355);

        jLabel6.setText("Descrição:");
        Anuncio.add(jLabel6);
        jLabel6.setBounds(320, 170, 50, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Senha.png"))); // NOI18N
        Anuncio.add(jLabel7);
        jLabel7.setBounds(390, 400, 220, 34);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Titulo.png"))); // NOI18N
        Anuncio.add(jLabel9);
        jLabel9.setBounds(390, 100, 378, 34);

        jl_campoDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo descricao.png"))); // NOI18N
        Anuncio.add(jl_campoDescricao);
        jl_campoDescricao.setBounds(390, 150, 380, 220);

        jtf_NomeProduto.setBackground(new java.awt.Color(242, 242, 242));
        jtf_NomeProduto.setBorder(null);
        Anuncio.add(jtf_NomeProduto);
        jtf_NomeProduto.setBounds(400, 110, 360, 14);

        jtf_PrecoProduto.setEditable(false);
        jtf_PrecoProduto.setBorder(null);
        jtf_PrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_PrecoProdutoActionPerformed(evt);
            }
        });
        Anuncio.add(jtf_PrecoProduto);
        jtf_PrecoProduto.setBounds(400, 410, 200, 20);

        jtf_NomeProduto1.setBackground(new java.awt.Color(242, 242, 242));
        jtf_NomeProduto1.setBorder(null);
        Anuncio.add(jtf_NomeProduto1);
        jtf_NomeProduto1.setBounds(400, 160, 360, 200);

        jRB_Novo.setText("Novo");
        Anuncio.add(jRB_Novo);
        jRB_Novo.setBounds(380, 480, 51, 23);

        jRB_usado.setText("usado");
        Anuncio.add(jRB_usado);
        jRB_usado.setBounds(380, 500, 55, 23);

        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Anuncio.add(jcb_estado);
        jcb_estado.setBounds(700, 400, 56, 20);

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit icon.png"))); // NOI18N
        btn_Editar.setContentAreaFilled(false);
        Anuncio.add(btn_Editar);
        btn_Editar.setBounds(209, 604, 97, 73);

        btn_cancelar.setText("Cancelar");
        Anuncio.add(btn_cancelar);
        btn_cancelar.setBounds(341, 654, 75, 23);

        btn_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        btn_cadastrar.setContentAreaFilled(false);
        Anuncio.add(btn_cadastrar);
        btn_cadastrar.setBounds(446, 604, 97, 73);

        getContentPane().add(Anuncio, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_PrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_PrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_PrecoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anuncio;
    private javax.swing.JPanel Reserva;
    private javax.swing.JPanel Venda;
    private javax.swing.JButton ___;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_aceitar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_recusar;
    private javax.swing.JPanel inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_conservacao;
    private javax.swing.JLabel jLabel_estadoVenda;
    private javax.swing.JLabel jLabel_preco;
    private javax.swing.JRadioButton jRB_Novo;
    private javax.swing.JRadioButton jRB_usado;
    private javax.swing.JComboBox<String> jcb_estado;
    private javax.swing.JLabel jl_Imagem;
    private javax.swing.JLabel jl_campoDescricao;
    private javax.swing.JLabel jl_img;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JTextField jtf_NomeProduto;
    private javax.swing.JTextField jtf_NomeProduto1;
    private javax.swing.JTextField jtf_PrecoProduto;
    // End of variables declaration//GEN-END:variables
}
