/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gabri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_fechar = new javax.swing.JButton();
        btn_Logar = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Botton = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        Top = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(328, 513));
        setMinimumSize(new java.awt.Dimension(328, 513));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(328, 513));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close button.png"))); // NOI18N
        btn_fechar.setBorder(null);
        btn_fechar.setBorderPainted(false);
        btn_fechar.setContentAreaFilled(false);
        getContentPane().add(btn_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 8, 30, -1));

        btn_Logar.setBackground(new java.awt.Color(169, 45, 215));
        btn_Logar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logar.setText("Logar");
        btn_Logar.setBorder(null);
        btn_Logar.setBorderPainted(false);
        btn_Logar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_Logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 350, 30));

        btn_Cadastrar.setBackground(new java.awt.Color(169, 45, 215));
        btn_Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cadastrar.setText("Cadastre-se!");
        btn_Cadastrar.setBorder(null);
        btn_Cadastrar.setBorderPainted(false);
        btn_Cadastrar.setMaximumSize(new java.awt.Dimension(345, 25));
        btn_Cadastrar.setMinimumSize(new java.awt.Dimension(345, 25));
        getContentPane().add(btn_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 450, 360, 30));

        btn_Sair.setBackground(new java.awt.Color(169, 45, 215));
        btn_Sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sair.setText("Sair");
        btn_Sair.setBorder(null);
        btn_Sair.setBorderPainted(false);
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, 350, 30));

        jtfUsuario.setBorder(null);
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 20));

        jpfSenha.setBorder(null);
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quer desapegar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olx.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 140));

        Botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login topo.png"))); // NOI18N
        Botton.setText("jLabel4");
        getContentPane().add(Botton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 360, -1));
        Botton.getAccessibleContext().setAccessibleName("design_topo");

        Usuario.setBackground(new java.awt.Color(255, 255, 255));
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jtf_login.png"))); // NOI18N
        Usuario.setText("Usuario:");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 270, 40));

        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jtf_pass.png"))); // NOI18N
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        Top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login topo.png"))); // NOI18N
        getContentPane().add(Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login fundo.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        jtfUsuario.setText("");
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Botton;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Top;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Logar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
