/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Usuario;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        btn_buscar.setIcon(BuscarSelected);

    }

    public void StatusAnuncios(String Status) {
        //Fazer uma busca no banco para verificar o status de cada pedido para o id daquele usuario

        

        switch (Status) {
            case "Reservado":
                btn_Reservas.setIcon(Reservar);
                
                
            case "Desapegar":
                //
                btn_Reservas.setIcon(CancelarReserva);
                
            case "Interessado":
                btn_Reservas.setIcon(Desapegar);
                
            default:
                break;
        }

       
    }

    //Icones do menu lateral
    ImageIcon Buscar2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/Buscar.png"));
    ImageIcon MeuCadastro2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeuCadastro.png"));
    ImageIcon Desapegar2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/Desapegar.png"));
    ImageIcon MeusPedidos2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeusPedidos.png"));
    ImageIcon MeusAnuncios2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeusAnuncios.png"));
    ImageIcon Sair2 = new ImageIcon(getClass().getResource("/Img/MenuLateral/Sair.png"));

//Icones do menu lateral se for selecionado
    ImageIcon BuscarSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/BuscarSelected.png"));
    ImageIcon MeuCadastroSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeuCadastroSelected.png"));
    ImageIcon DesapegarSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/DesapegarSelected.png"));
    ImageIcon MeusPedidosSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeusPedidosSelected.png"));
    ImageIcon MeusAnunciosSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/MeusAnunciosSelected.png"));
    ImageIcon SairSelected = new ImageIcon(getClass().getResource("/Img/MenuLateral/SairSelected.png"));

    //botoes do menu meus anuncios
    ImageIcon Reservar = new ImageIcon(getClass().getResource("/Img/Reservar icon.png"));
    ImageIcon CancelarReserva = new ImageIcon(getClass().getResource("/Img/CancelarReserva.png"));
    ImageIcon Desapegar = new ImageIcon(getClass().getResource("/Img/Desepegar.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bt_fechar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        BarraTop = new javax.swing.JLabel();
        bt_meuCadastro = new javax.swing.JButton();
        bt_desapegar = new javax.swing.JButton();
        bt_meusPedidos = new javax.swing.JButton();
        bt_meusAnuncios = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        Inicio_buscar = new javax.swing.JPanel();
        jLabelB_Categoria = new javax.swing.JLabel();
        jLabelB_Regiao = new javax.swing.JLabel();
        jLabelB_Estado = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxRegiao = new javax.swing.JComboBox<>();
        jRadioButtonNovo = new javax.swing.JRadioButton();
        jRadioButtonUsado = new javax.swing.JRadioButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bt_Lupa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        Desapego = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_inserirFoto = new javax.swing.JButton();
        bj_Categoria = new javax.swing.JComboBox<>();
        jLabel_Desapego = new javax.swing.JLabel();
        lblImagemProd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_valor = new javax.swing.JLabel();
        jl_condicaoProduto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoTitulo = new javax.swing.JLabel();
        CampoPreco = new javax.swing.JLabel();
        jrb_Novo = new javax.swing.JRadioButton();
        jrb_Usado = new javax.swing.JRadioButton();
        jtf_titulo = new javax.swing.JTextField();
        jtf_titulo1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_descricao = new javax.swing.JTextArea();
        jLabelDescricao = new javax.swing.JLabel();
        FundoD = new javax.swing.JLabel();
        jtf_titulo2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_descricao1 = new javax.swing.JTextArea();
        MeuCadastro = new javax.swing.JPanel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jtf_Nome = new javax.swing.JTextField();
        jtf_Cidade = new javax.swing.JTextField();
        jtf_Bairro = new javax.swing.JTextField();
        jtf_Email = new javax.swing.JTextField();
        jtf_Usuario = new javax.swing.JTextField();
        jtf_Senha = new javax.swing.JTextField();
        btn_edit1 = new javax.swing.JButton();
        btn_limpar1 = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        jtf_Cancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        JlCidade = new javax.swing.JLabel();
        JlTelefone = new javax.swing.JLabel();
        JlUsuario = new javax.swing.JLabel();
        JlEmail = new javax.swing.JLabel();
        JlSenha = new javax.swing.JLabel();
        jl_MeuCadastro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jc_estado = new javax.swing.JComboBox<>();
        Jlbackground = new javax.swing.JLabel();
        MeusAnuncios = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btn_Reservas = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fundoExibiranuncio = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Pesquisa = new javax.swing.JLabel();
        btn_busca = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        MeusPedidos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Pesquisa1 = new javax.swing.JLabel();
        btn_busca1 = new javax.swing.JButton();
        btn_CancelarPedido = new javax.swing.JButton();
        btn_comprar = new javax.swing.JButton();
        jLabel_fotoProduto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        ExibirAnuncio = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelNovo_Usado = new javax.swing.JLabel();
        jLabelDataEstado = new javax.swing.JLabel();
        bt_comprar = new javax.swing.JButton();
        bt_reservar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1369, 730));
        setMinimumSize(new java.awt.Dimension(1369, 730));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1369, 730));
        getContentPane().setLayout(null);

        bt_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Botao fechar.png"))); // NOI18N
        bt_fechar.setBorderPainted(false);
        bt_fechar.setContentAreaFilled(false);
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });
        getContentPane().add(bt_fechar);
        bt_fechar.setBounds(1316, 0, 50, 50);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo novo.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(10, 0, 50, 50);

        nomeUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeUser.setForeground(new java.awt.Color(255, 153, 0));
        nomeUser.setText("Nome do usuário aqui");
        getContentPane().add(nomeUser);
        nomeUser.setBounds(65, 16, 210, 22);

        BarraTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra superior.png"))); // NOI18N
        getContentPane().add(BarraTop);
        BarraTop.setBounds(0, 0, 1370, 50);

        bt_meuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/MeuCadastro.png"))); // NOI18N
        bt_meuCadastro.setBorderPainted(false);
        bt_meuCadastro.setContentAreaFilled(false);
        bt_meuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_meuCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(bt_meuCadastro);
        bt_meuCadastro.setBounds(-7, 200, 310, 75);

        bt_desapegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/Desapegar.png"))); // NOI18N
        bt_desapegar.setBorderPainted(false);
        bt_desapegar.setContentAreaFilled(false);
        bt_desapegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desapegarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_desapegar);
        bt_desapegar.setBounds(-7, 310, 310, 75);

        bt_meusPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/MeusPedidos.png"))); // NOI18N
        bt_meusPedidos.setBorderPainted(false);
        bt_meusPedidos.setContentAreaFilled(false);
        bt_meusPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_meusPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(bt_meusPedidos);
        bt_meusPedidos.setBounds(-7, 420, 310, 75);

        bt_meusAnuncios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/MeusAnuncios.png"))); // NOI18N
        bt_meusAnuncios.setBorderPainted(false);
        bt_meusAnuncios.setContentAreaFilled(false);
        bt_meusAnuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_meusAnunciosActionPerformed(evt);
            }
        });
        getContentPane().add(bt_meusAnuncios);
        bt_meusAnuncios.setBounds(-7, 530, 310, 75);

        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/Sair.png"))); // NOI18N
        bt_sair.setBorderPainted(false);
        bt_sair.setContentAreaFilled(false);
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sair);
        bt_sair.setBounds(-7, 640, 310, 70);

        btn_buscar.setBackground(new java.awt.Color(242, 242, 242));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuLateral/Buscar.png"))); // NOI18N
        btn_buscar.setBorder(null);
        btn_buscar.setBorderPainted(false);
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar);
        btn_buscar.setBounds(-2, 90, 300, 67);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fundo menu.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 350, 730);

        Principal.setLayout(new java.awt.CardLayout());

        Inicio_buscar.setLayout(null);

        jLabelB_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelB_Categoria.setText("Categoria:");
        Inicio_buscar.add(jLabelB_Categoria);
        jLabelB_Categoria.setBounds(650, 50, 63, 20);

        jLabelB_Regiao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelB_Regiao.setText("Região:");
        Inicio_buscar.add(jLabelB_Regiao);
        jLabelB_Regiao.setBounds(670, 20, 46, 17);

        jLabelB_Estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelB_Estado.setText("Estado:");
        Inicio_buscar.add(jLabelB_Estado);
        jLabelB_Estado.setBounds(810, 20, 48, 17);

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        Inicio_buscar.add(jComboBoxCategoria);
        jComboBoxCategoria.setBounds(721, 50, 70, 23);

        jComboBoxRegiao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxRegiao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Inicio_buscar.add(jComboBoxRegiao);
        jComboBoxRegiao.setBounds(721, 18, 70, 23);

        jRadioButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonNovo.setText("Novo");
        jRadioButtonNovo.setContentAreaFilled(false);
        Inicio_buscar.add(jRadioButtonNovo);
        jRadioButtonNovo.setBounds(860, 10, 70, 25);

        jRadioButtonUsado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonUsado.setText("Usado");
        jRadioButtonUsado.setContentAreaFilled(false);
        jRadioButtonUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUsadoActionPerformed(evt);
            }
        });
        Inicio_buscar.add(jRadioButtonUsado);
        jRadioButtonUsado.setBounds(860, 30, 70, 25);

        jTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscar.setBorder(null);
        Inicio_buscar.add(jTextFieldBuscar);
        jTextFieldBuscar.setBounds(50, 30, 590, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar/CAMPO BUSCA.png"))); // NOI18N
        Inicio_buscar.add(jLabel10);
        jLabel10.setBounds(40, 20, 610, 50);

        bt_Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar/botao lupa.png"))); // NOI18N
        bt_Lupa.setBorderPainted(false);
        bt_Lupa.setContentAreaFilled(false);
        Inicio_buscar.add(bt_Lupa);
        bt_Lupa.setBounds(940, 20, 60, 43);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Inicio_buscar.add(jScrollPane2);
        jScrollPane2.setBounds(40, 90, 950, 520);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íco-Imovel copiar 6.png"))); // NOI18N
        Inicio_buscar.add(background1);
        background1.setBounds(0, -40, 1025, 720);

        Principal.add(Inicio_buscar, "Inicio");

        Desapego.setLayout(null);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel icon.png"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);
        Desapego.add(btn_cancelar);
        btn_cancelar.setBounds(640, 570, 80, 80);

        btn_limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        btn_limpar.setBorderPainted(false);
        btn_limpar.setContentAreaFilled(false);
        Desapego.add(btn_limpar);
        btn_limpar.setBounds(560, 570, 80, 80);

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        Desapego.add(btn_save);
        btn_save.setBounds(470, 570, 97, 80);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit icon.png"))); // NOI18N
        btn_edit.setBorderPainted(false);
        btn_edit.setContentAreaFilled(false);
        Desapego.add(btn_edit);
        btn_edit.setBounds(390, 570, 97, 80);

        btn_inserirFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inserir foto icon.png"))); // NOI18N
        btn_inserirFoto.setBorderPainted(false);
        btn_inserirFoto.setContentAreaFilled(false);
        Desapego.add(btn_inserirFoto);
        btn_inserirFoto.setBounds(180, 470, 120, 41);

        bj_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bj_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Desapego.add(bj_Categoria);
        bj_Categoria.setBounds(560, 500, 210, 20);

        jLabel_Desapego.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel_Desapego.setForeground(new java.awt.Color(247, 130, 50));
        jLabel_Desapego.setText("Desapego");
        Desapego.add(jLabel_Desapego);
        jLabel_Desapego.setBounds(420, 20, 230, 70);

        lblImagemProd.setBackground(new java.awt.Color(242, 242, 242));
        lblImagemProd.setToolTipText("");
        lblImagemProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Desapego.add(lblImagemProd);
        lblImagemProd.setBounds(90, 130, 290, 340);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Titulo:");
        Desapego.add(jLabel3);
        jLabel3.setBounds(560, 120, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descricão:");
        Desapego.add(jLabel4);
        jLabel4.setBounds(560, 180, 70, 17);

        jl_valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_valor.setText("Preço:");
        Desapego.add(jl_valor);
        jl_valor.setBounds(560, 420, 40, 17);

        jl_condicaoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_condicaoProduto.setText("O produto é");
        Desapego.add(jl_condicaoProduto);
        jl_condicaoProduto.setBounds(800, 440, 80, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Categoria:");
        Desapego.add(jLabel1);
        jLabel1.setBounds(560, 480, 70, 17);

        CampoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Titulo.png"))); // NOI18N
        Desapego.add(CampoTitulo);
        CampoTitulo.setBounds(560, 140, 390, 34);

        CampoPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Valor campo.png"))); // NOI18N
        Desapego.add(CampoPreco);
        CampoPreco.setBounds(560, 440, 200, 34);

        jrb_Novo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrb_Novo.setText("Novo");
        jrb_Novo.setContentAreaFilled(false);
        Desapego.add(jrb_Novo);
        jrb_Novo.setBounds(800, 460, 61, 25);

        jrb_Usado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrb_Usado.setText("Usado");
        jrb_Usado.setContentAreaFilled(false);
        Desapego.add(jrb_Usado);
        jrb_Usado.setBounds(860, 460, 80, 25);

        jtf_titulo.setBackground(new java.awt.Color(242, 242, 242));
        jtf_titulo.setBorder(null);
        Desapego.add(jtf_titulo);
        jtf_titulo.setBounds(568, 142, 360, 30);

        jtf_titulo1.setBackground(new java.awt.Color(242, 242, 242));
        jtf_titulo1.setBorder(null);
        Desapego.add(jtf_titulo1);
        jtf_titulo1.setBounds(568, 142, 360, 30);

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setBorder(null);
        Desapego.add(jTextField1);
        jTextField1.setBounds(570, 450, 170, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(247, 130, 50));
        jLabel23.setText("*");
        Desapego.add(jLabel23);
        jLabel23.setBounds(550, 170, 10, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(247, 130, 50));
        jLabel22.setText("*");
        Desapego.add(jLabel22);
        jLabel22.setBounds(550, 410, 10, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 130, 50));
        jLabel21.setText("*");
        Desapego.add(jLabel21);
        jLabel21.setBounds(550, 470, 10, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(247, 130, 50));
        jLabel20.setText("*");
        Desapego.add(jLabel20);
        jLabel20.setBounds(550, 110, 10, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 130, 50));
        jLabel19.setText("*");
        Desapego.add(jLabel19);
        jLabel19.setBounds(170, 470, 10, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(247, 130, 50));
        jLabel18.setText("Campos Obrigatorios*");
        Desapego.add(jLabel18);
        jLabel18.setBounds(90, 80, 150, 17);

        jta_descricao.setBackground(new java.awt.Color(242, 242, 242));
        jta_descricao.setColumns(20);
        jta_descricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jta_descricao.setRows(5);
        jta_descricao.setBorder(null);
        jScrollPane1.setViewportView(jta_descricao);

        Desapego.add(jScrollPane1);
        jScrollPane1.setBounds(570, 200, 360, 200);

        jLabelDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo descricao.png"))); // NOI18N
        Desapego.add(jLabelDescricao);
        jLabelDescricao.setBounds(560, 190, 390, 220);

        FundoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íco-Imovel copiar 6.png"))); // NOI18N
        Desapego.add(FundoD);
        FundoD.setBounds(0, -50, 1030, 730);

        jtf_titulo2.setBackground(new java.awt.Color(242, 242, 242));
        jtf_titulo2.setBorder(null);
        Desapego.add(jtf_titulo2);
        jtf_titulo2.setBounds(568, 142, 360, 30);

        jta_descricao1.setBackground(new java.awt.Color(242, 242, 242));
        jta_descricao1.setColumns(20);
        jta_descricao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jta_descricao1.setRows(5);
        jta_descricao1.setBorder(null);
        jScrollPane4.setViewportView(jta_descricao1);

        Desapego.add(jScrollPane4);
        jScrollPane4.setBounds(570, 200, 360, 200);

        Principal.add(Desapego, "Desapegar");

        MeuCadastro.setLayout(null);

        jLabelNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeCompleto.setText("Nome:");
        MeuCadastro.add(jLabelNomeCompleto);
        jLabelNomeCompleto.setBounds(100, 120, 50, 30);

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCidade.setText("Cidade:");
        MeuCadastro.add(jLabelCidade);
        jLabelCidade.setBounds(100, 270, 46, 20);

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBairro.setText("Bairro:");
        MeuCadastro.add(jLabelBairro);
        jLabelBairro.setBounds(100, 200, 50, 30);

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        MeuCadastro.add(jLabelEstado);
        jLabelEstado.setBounds(100, 350, 50, 17);

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefone.setText("Telefone:");
        MeuCadastro.add(jLabelTelefone);
        jLabelTelefone.setBounds(640, 190, 60, 20);

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        MeuCadastro.add(jLabelEmail);
        jLabelEmail.setBounds(640, 120, 50, 17);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        MeuCadastro.add(jLabelUsuario);
        jLabelUsuario.setBounds(640, 260, 60, 17);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        MeuCadastro.add(jLabelSenha);
        jLabelSenha.setBounds(640, 320, 50, 17);

        jtfTelefone.setBackground(new java.awt.Color(242, 242, 242));
        jtfTelefone.setBorder(null);
        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        MeuCadastro.add(jtfTelefone);
        jtfTelefone.setBounds(650, 220, 310, 19);

        jtf_Nome.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Nome.setBorder(null);
        jtf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomeActionPerformed(evt);
            }
        });
        MeuCadastro.add(jtf_Nome);
        jtf_Nome.setBounds(110, 150, 460, 20);

        jtf_Cidade.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Cidade.setBorder(null);
        MeuCadastro.add(jtf_Cidade);
        jtf_Cidade.setBounds(110, 300, 310, 16);

        jtf_Bairro.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Bairro.setBorder(null);
        MeuCadastro.add(jtf_Bairro);
        jtf_Bairro.setBounds(110, 230, 310, 20);

        jtf_Email.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Email.setBorder(null);
        MeuCadastro.add(jtf_Email);
        jtf_Email.setBounds(650, 150, 320, 20);

        jtf_Usuario.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Usuario.setBorder(null);
        MeuCadastro.add(jtf_Usuario);
        jtf_Usuario.setBounds(650, 290, 200, 20);

        jtf_Senha.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Senha.setBorder(null);
        MeuCadastro.add(jtf_Senha);
        jtf_Senha.setBounds(650, 350, 200, 20);

        btn_edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit icon.png"))); // NOI18N
        btn_edit1.setBorderPainted(false);
        btn_edit1.setContentAreaFilled(false);
        MeuCadastro.add(btn_edit1);
        btn_edit1.setBounds(300, 551, 97, 73);

        btn_limpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        btn_limpar1.setBorderPainted(false);
        btn_limpar1.setContentAreaFilled(false);
        MeuCadastro.add(btn_limpar1);
        btn_limpar1.setBounds(510, 549, 80, 70);

        btn_Cadastrar.setBackground(new java.awt.Color(242, 242, 242));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save icon.png"))); // NOI18N
        btn_Cadastrar.setContentAreaFilled(false);
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        MeuCadastro.add(btn_Cadastrar);
        btn_Cadastrar.setBounds(400, 551, 97, 70);

        jtf_Cancelar.setBackground(new java.awt.Color(242, 242, 242));
        jtf_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel icon.png"))); // NOI18N
        jtf_Cancelar.setContentAreaFilled(false);
        MeuCadastro.add(jtf_Cancelar);
        jtf_Cancelar.setBounds(600, 550, 97, 70);

        jLabelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Nome.png"))); // NOI18N
        MeuCadastro.add(jLabelNome);
        jLabelNome.setBounds(100, 140, 480, 40);

        JlCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Cidade.png"))); // NOI18N
        MeuCadastro.add(JlCidade);
        JlCidade.setBounds(100, 290, 340, 34);

        JlTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo telefone.png"))); // NOI18N
        MeuCadastro.add(JlTelefone);
        JlTelefone.setBounds(640, 210, 350, 34);

        JlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo user.png"))); // NOI18N
        MeuCadastro.add(JlUsuario);
        JlUsuario.setBounds(640, 280, 220, 34);

        JlEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Email.png"))); // NOI18N
        MeuCadastro.add(JlEmail);
        JlEmail.setBounds(640, 142, 350, 34);

        JlSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Senha2.png"))); // NOI18N
        MeuCadastro.add(JlSenha);
        JlSenha.setBounds(640, 340, 220, 34);

        jl_MeuCadastro.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jl_MeuCadastro.setForeground(new java.awt.Color(250, 130, 50));
        jl_MeuCadastro.setText("Meu Cadastro");
        MeuCadastro.add(jl_MeuCadastro);
        jl_MeuCadastro.setBounds(420, 30, 330, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Bairro.png"))); // NOI18N
        MeuCadastro.add(jLabel2);
        jLabel2.setBounds(100, 220, 340, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 130, 50));
        jLabel8.setText("Campos Obrigatorios*");
        MeuCadastro.add(jLabel8);
        jLabel8.setBounds(100, 90, 150, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 130, 50));
        jLabel9.setText("*");
        MeuCadastro.add(jLabel9);
        jLabel9.setBounds(90, 200, 10, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 130, 50));
        jLabel12.setText("*");
        MeuCadastro.add(jLabel12);
        jLabel12.setBounds(90, 260, 10, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(247, 130, 50));
        jLabel11.setText("*");
        MeuCadastro.add(jLabel11);
        jLabel11.setBounds(90, 120, 10, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(247, 130, 50));
        jLabel13.setText("*");
        MeuCadastro.add(jLabel13);
        jLabel13.setBounds(630, 110, 10, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(247, 130, 50));
        jLabel14.setText("*");
        MeuCadastro.add(jLabel14);
        jLabel14.setBounds(90, 340, 10, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(247, 130, 50));
        jLabel15.setText("*");
        MeuCadastro.add(jLabel15);
        jLabel15.setBounds(630, 310, 10, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(247, 130, 50));
        jLabel16.setText("*");
        MeuCadastro.add(jLabel16);
        jLabel16.setBounds(630, 250, 10, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(247, 130, 50));
        jLabel17.setText("*");
        MeuCadastro.add(jLabel17);
        jLabel17.setBounds(630, 180, 10, 30);

        jc_estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jc_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MeuCadastro.add(jc_estado);
        jc_estado.setBounds(170, 350, 80, 23);

        Jlbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpeg"))); // NOI18N
        MeuCadastro.add(Jlbackground);
        Jlbackground.setBounds(0, -48, 1030, 728);

        Principal.add(MeuCadastro, "MeuCadastro");

        MeusAnuncios.setLayout(null);

        jLabel27.setText("status da reserva/compra aqui");
        MeusAnuncios.add(jLabel27);
        jLabel27.setBounds(280, 260, 190, 16);

        btn_Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reservar icon.png"))); // NOI18N
        btn_Reservas.setBorderPainted(false);
        btn_Reservas.setContentAreaFilled(false);
        btn_Reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReservasActionPerformed(evt);
            }
        });
        MeusAnuncios.add(btn_Reservas);
        btn_Reservas.setBounds(320, 320, 140, 30);

        jLabel24.setText("Data do anuncio aqui");
        MeusAnuncios.add(jLabel24);
        jLabel24.setBounds(370, 300, 130, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Preço");
        MeusAnuncios.add(jLabel26);
        jLabel26.setBounds(280, 280, 120, 22);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Titulo aqui");
        MeusAnuncios.add(jLabel25);
        jLabel25.setBounds(280, 230, 120, 22);

        fundoExibiranuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo meus anuncios.png"))); // NOI18N
        MeusAnuncios.add(fundoExibiranuncio);
        fundoExibiranuncio.setBounds(100, 230, 402, 125);

        jTextField2.setBackground(new java.awt.Color(242, 242, 242));
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        MeusAnuncios.add(jTextField2);
        jTextField2.setBounds(60, 82, 440, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 130, 50));
        jLabel6.setText("Meus Anuncios");
        MeusAnuncios.add(jLabel6);
        jLabel6.setBounds(330, 10, 400, 61);

        jLabel_Pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Nome.png"))); // NOI18N
        MeusAnuncios.add(jLabel_Pesquisa);
        jLabel_Pesquisa.setBounds(40, 80, 480, 34);

        btn_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar/botao lupa.png"))); // NOI18N
        btn_busca.setBorderPainted(false);
        btn_busca.setContentAreaFilled(false);
        MeusAnuncios.add(btn_busca);
        btn_busca.setBounds(510, 75, 73, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íco-Imovel copiar 6.png"))); // NOI18N
        MeusAnuncios.add(background);
        background.setBounds(0, -50, 1040, 726);

        Principal.add(MeusAnuncios, "MeusAnuncios");
        MeusAnuncios.getAccessibleContext().setAccessibleName("");

        MeusPedidos.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 130, 50));
        jLabel7.setText("Meus Pedidos");
        MeusPedidos.add(jLabel7);
        jLabel7.setBounds(320, 10, 420, 61);

        jLabel_Pesquisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campo Nome.png"))); // NOI18N
        MeusPedidos.add(jLabel_Pesquisa1);
        jLabel_Pesquisa1.setBounds(130, 90, 480, 34);

        btn_busca1.setText("busca");
        MeusPedidos.add(btn_busca1);
        btn_busca1.setBounds(630, 100, 73, 25);

        btn_CancelarPedido.setText("Cancelar pedido");
        MeusPedidos.add(btn_CancelarPedido);
        btn_CancelarPedido.setBounds(570, 220, 210, 25);

        btn_comprar.setText("OK para Pergunta");
        MeusPedidos.add(btn_comprar);
        btn_comprar.setBounds(570, 300, 220, 25);

        jLabel_fotoProduto.setText("FOTO E DESCRIÇÃO DO PRODUTO");
        MeusPedidos.add(jLabel_fotoProduto);
        jLabel_fotoProduto.setBounds(190, 220, 370, 16);

        jLabel5.setText("INDICAR SE FUI AUTORIZADO PRA COMPRAR OU RECUSADO");
        MeusPedidos.add(jLabel5);
        jLabel5.setBounds(100, 300, 380, 16);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Íco-Imovel copiar 6.png"))); // NOI18N
        MeusPedidos.add(background3);
        background3.setBounds(0, -50, 1040, 726);

        Principal.add(MeusPedidos, "MeusPedidos");

        ExibirAnuncio.setLayout(null);

        jLabelTitulo.setBackground(new java.awt.Color(250, 250, 250));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(247, 130, 50));
        jLabelTitulo.setText("Titulo AQUI");
        ExibirAnuncio.add(jLabelTitulo);
        jLabelTitulo.setBounds(580, -10, 270, 150);

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ExibirAnuncio/OLX FOTO.png"))); // NOI18N
        ExibirAnuncio.add(jLabelFoto);
        jLabelFoto.setBounds(20, 90, 350, 450);

        jLabelPreco.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(144, 39, 175));
        jLabelPreco.setText("R$ 999999,00");
        jLabelPreco.setToolTipText("");
        ExibirAnuncio.add(jLabelPreco);
        jLabelPreco.setBounds(800, 500, 220, 37);

        jLabelNovo_Usado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelNovo_Usado.setForeground(new java.awt.Color(132, 211, 61));
        jLabelNovo_Usado.setText("Novo/Usado");
        ExibirAnuncio.add(jLabelNovo_Usado);
        jLabelNovo_Usado.setBounds(910, 540, 110, 25);

        jLabelDataEstado.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelDataEstado.setText("Exibir a data e estado dessa forma(18 de Novembro de 2017   SP)");
        ExibirAnuncio.add(jLabelDataEstado);
        jLabelDataEstado.setBounds(20, 550, 510, 19);

        bt_comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ExibirAnuncio/botao Comprar.png"))); // NOI18N
        bt_comprar.setBorderPainted(false);
        bt_comprar.setContentAreaFilled(false);
        bt_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comprarActionPerformed(evt);
            }
        });
        ExibirAnuncio.add(bt_comprar);
        bt_comprar.setBounds(290, 620, 230, 47);

        bt_reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ExibirAnuncio/botao reservar.png"))); // NOI18N
        bt_reservar.setBorderPainted(false);
        bt_reservar.setContentAreaFilled(false);
        bt_reservar.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        ExibirAnuncio.add(bt_reservar);
        bt_reservar.setBounds(570, 620, 230, 47);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        ExibirAnuncio.add(jScrollPane3);
        jScrollPane3.setBounds(460, 120, 480, 360);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ExibirAnuncio/Fundo.png"))); // NOI18N
        ExibirAnuncio.add(background2);
        background2.setBounds(0, 0, 1025, 680);

        Principal.add(ExibirAnuncio, "ExibirAnuncio");
        ExibirAnuncio.getAccessibleContext().setAccessibleName("");

        getContentPane().add(Principal);
        Principal.setBounds(340, 50, 1030, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_meuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_meuCadastroActionPerformed
        if (!bt_meuCadastro.isSelected()) {
            btn_buscar.setIcon(Buscar2);
            bt_meuCadastro.setIcon(MeuCadastroSelected);
            bt_desapegar.setIcon(Desapegar2);
            bt_meusPedidos.setIcon(MeusPedidos2);
            bt_meusAnuncios.setIcon(MeusAnuncios2);
            bt_sair.setIcon(Sair2);

        }

        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "MeuCadastro");

    }//GEN-LAST:event_bt_meuCadastroActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void jtf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomeActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        if (!bt_sair.isSelected()) {
            btn_buscar.setIcon(Buscar2);
            bt_meuCadastro.setIcon(MeuCadastro2);
            bt_desapegar.setIcon(Desapegar2);
            bt_meusPedidos.setIcon(MeusPedidos2);
            bt_meusAnuncios.setIcon(MeusAnuncios2);
            bt_sair.setIcon(SairSelected);

        }

        Login login = new Login();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_desapegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desapegarActionPerformed
        if (!bt_desapegar.isSelected()) {
            btn_buscar.setIcon(Buscar2);
            bt_meuCadastro.setIcon(MeuCadastro2);
            bt_desapegar.setIcon(DesapegarSelected);
            bt_meusPedidos.setIcon(MeusPedidos2);
            bt_meusAnuncios.setIcon(MeusAnuncios2);
            bt_sair.setIcon(Sair2);

        }

        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "Desapegar");
    }//GEN-LAST:event_bt_desapegarActionPerformed

    private void bt_meusAnunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_meusAnunciosActionPerformed
        if (!bt_meusAnuncios.isSelected()) {
            btn_buscar.setIcon(Buscar2);
            bt_meuCadastro.setIcon(MeuCadastro2);
            bt_desapegar.setIcon(Desapegar2);
            bt_meusPedidos.setIcon(MeusPedidos2);
            bt_meusAnuncios.setIcon(MeusAnunciosSelected);
            bt_sair.setIcon(Sair2);

        }

        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "MeusAnuncios");
    }//GEN-LAST:event_bt_meusAnunciosActionPerformed

    private void jtf_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorActionPerformed

    private void btn_inicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio3ActionPerformed
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "Inicio");
    }//GEN-LAST:event_btn_inicio3ActionPerformed

    private void btn_inicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio2ActionPerformed
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "Inicio");
    }//GEN-LAST:event_btn_inicio2ActionPerformed

    private void btn_inicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio1ActionPerformed

    }//GEN-LAST:event_btn_inicio1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (!btn_buscar.isSelected()) {
            btn_buscar.setIcon(BuscarSelected);
            bt_meuCadastro.setIcon(MeuCadastro2);
            bt_desapegar.setIcon(Desapegar2);
            bt_meusPedidos.setIcon(MeusPedidos2);
            bt_meusAnuncios.setIcon(MeusAnuncios2);
            bt_sair.setIcon(Sair2);

        }

        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "Inicio");
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void bt_meusPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_meusPedidosActionPerformed
        if (!bt_meusPedidos.isSelected()) {
            btn_buscar.setIcon(Buscar2);
            bt_meuCadastro.setIcon(MeuCadastro2);
            bt_desapegar.setIcon(Desapegar2);
            bt_meusPedidos.setIcon(MeusPedidosSelected);
            bt_meusAnuncios.setIcon(MeusAnuncios2);
            bt_sair.setIcon(Sair2);
        }
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal, "MeusPedidos");
    }//GEN-LAST:event_bt_meusPedidosActionPerformed

    private void jRadioButtonUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUsadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonUsadoActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void bt_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_comprarActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_ReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReservasActionPerformed
//        int dialogButton = 0;
//
//        //anuncio com interesse de reserva
//        if (StatusAnuncios == 1) {
//            Reservas reservas = new Reservas();
//            reservas.setVisible(true);
//
////anuncio ja reservado
//        } else if (StatusAnuncios() == 2) {
//            dialogButton = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar a reserva para o +nome+ ?", "Cancelar reserva!", JOptionPane.YES_NO_OPTION);
//        }
//        if (dialogButton == JOptionPane.YES_OPTION) {
//            //Alterar o status no banco para nao reservado para disponivel.
//        } //Alguem quer comprar o produto
//        else if (StatusAnuncios() == 3) {
//            dialogButton = JOptionPane.showConfirmDialog(null, "+nome+ quer comprar seu produto!!", "Desapegar!", JOptionPane.YES_NO_OPTION);
//        }
//        if (dialogButton == JOptionPane.YES_OPTION) {
//            //Alterar o status no banco para vendido, ou apagar do banco o produto.
//        }
//

    }//GEN-LAST:event_btn_ReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuario = new Usuario();
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraTop;
    private javax.swing.JLabel CampoPreco;
    private javax.swing.JLabel CampoTitulo;
    private javax.swing.JPanel Desapego;
    private javax.swing.JPanel ExibirAnuncio;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel FundoD;
    private javax.swing.JPanel Inicio_buscar;
    private javax.swing.JLabel JlCidade;
    private javax.swing.JLabel JlEmail;
    private javax.swing.JLabel JlSenha;
    private javax.swing.JLabel JlTelefone;
    private javax.swing.JLabel JlUsuario;
    private javax.swing.JLabel Jlbackground;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MeuCadastro;
    private javax.swing.JPanel MeusAnuncios;
    private javax.swing.JPanel MeusPedidos;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JComboBox<String> bj_Categoria;
    private javax.swing.JButton bt_Lupa;
    private javax.swing.JButton bt_comprar;
    private javax.swing.JButton bt_desapegar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_meuCadastro;
    private javax.swing.JButton bt_meusAnuncios;
    private javax.swing.JButton bt_meusPedidos;
    private javax.swing.JButton bt_reservar;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_CancelarPedido;
    private javax.swing.JButton btn_Reservas;
    private javax.swing.JButton btn_busca;
    private javax.swing.JButton btn_busca1;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_comprar;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_edit1;
    private javax.swing.JButton btn_inserirFoto;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_limpar1;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fundoExibiranuncio;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxRegiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelB_Categoria;
    private javax.swing.JLabel jLabelB_Estado;
    private javax.swing.JLabel jLabelB_Regiao;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataEstado;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNovo_Usado;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabel_Desapego;
    private javax.swing.JLabel jLabel_Pesquisa;
    private javax.swing.JLabel jLabel_Pesquisa1;
    private javax.swing.JLabel jLabel_fotoProduto;
    private javax.swing.JRadioButton jRadioButtonNovo;
    private javax.swing.JRadioButton jRadioButtonUsado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JComboBox<String> jc_estado;
    private javax.swing.JLabel jl_MeuCadastro;
    private javax.swing.JLabel jl_condicaoProduto;
    private javax.swing.JLabel jl_valor;
    private javax.swing.JRadioButton jrb_Novo;
    private javax.swing.JRadioButton jrb_Usado;
    private javax.swing.JTextArea jta_descricao;
    private javax.swing.JTextArea jta_descricao1;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JTextField jtf_Bairro;
    private javax.swing.JButton jtf_Cancelar;
    private javax.swing.JTextField jtf_Cidade;
    private javax.swing.JTextField jtf_Email;
    private javax.swing.JTextField jtf_Nome;
    private javax.swing.JTextField jtf_Senha;
    private javax.swing.JTextField jtf_Usuario;
    private javax.swing.JTextField jtf_titulo;
    private javax.swing.JTextField jtf_titulo1;
    private javax.swing.JTextField jtf_titulo2;
    private javax.swing.JLabel lblImagemProd;
    private javax.swing.JLabel nomeUser;
    // End of variables declaration//GEN-END:variables
}
